### ISSUE TITLE
Returns incorrect content type for Inference Endpoints

### ISSUE THREAD

**Issue by skorth** [jbilcke-hf/ai-comic-factory#11]
I played around with my own Inference Endpoint using _stabilityai/stable-diffusion-xl-base-1.0_ and the Inference API. The second one worked, my own Endpoint did not. In fact, the wrong content type (test/plain) seems to be delivered at the Inference Endpoints if it is not requested in the header. Just add a **"Accept": "image/png"** to the request header [here](https://github.com/jbilcke-hf/ai-comic-factory/blob/main/src/app/engine/render.ts#L259-L262), rebuild and everything works fine again.

**Comment by jbilcke** [comment]
Thanks for your suggestion, I am adding it as an environment variable + a config option

I have integrated it as part of my current WIP code (which will split the requests made to the LLM for a more progressive/smooth update - panels will be generated before the whole story is finished)


this new version should be deployed either today or tomorrow!

**Comment by jbilcke-hf** [comment]
Merged (see here https://github.com/jbilcke-hf/ai-comic-factory/blob/main/.env#L57 )
