### ISSUE TITLE
The story of Rostam and Esfandiar

### ISSUE THREAD

**Issue by aliaeifinahavandi** [jbilcke-hf/ai-comic-factory#17]
When Rostam bin Zal fought against Esfandiar, he was defeated by Esfandiar with the courage that Rostam had.

Several attacks took place between them, and in each attack Rostam was injured from Esfandiar. Because Esfandiar was strong and powerful, Rostam's attacks did not work on him, finally Rostam consulted with his father about Esfandiar, Zal said: you must prepare an arrow with two heads and aim at Esfandiar's eyes so that he becomes blind.

The reason has been said as follows: Esfandiar had a branch of a tree in his hand in his youth and hit an orphan child on the face with that branch and blinded him. So that orphan put the branch on the ground, during the war between Rostam and Esfandiar, Rostam took the same branch from the wood and cut a two-headed arrow and hit Esfandiar in his eyes and blinded him.

**Comment by jbilcke-hf** [comment]
Hi,

it looks like you are just posting a story as a GitHub issue.

the GitHub issues are meant to be used for support, submit bug reports, recommend changes in the code or ask questions.

I will close the issue, thank you
